-- 로컬 Postgres raw DB 스키마 — 노션 「RAW DB 스키마」(DDL 전문, DBML)를 옮긴 것.
--
-- 🔴 **이 파일은 로컬 검증용이다. 운영 스키마는 인프라가 세운다**(2026-08-16 확정).
--    운영에서 이 파일이 실행되는 일은 없고, 여기 있는 것과 운영이 어긋나면 **문서가
--    맞고 이 파일이 틀린 것**이다. 고칠 일이 생기면 코드가 아니라 노션을 먼저 볼 것
--    (`app/core/raw_schema.py` 머리말과 같은 규율. 그쪽은 sqlite 목 파이프라인용이다).
--
-- ⚠️ **정본에 없는 것은 여기 넣지 않는다.** 우리 코드가 추가로 요구하는 것(통합 뷰·
--    유니크 제약·버전 인덱스)은 `02_ai_read_model.sql` 에 따로 모아 뒀다 — 그 파일이
--    곧 **인프라에 요청해야 하는 목록**이라, 섞으면 무엇이 남의 것이고 무엇이 우리
--    요청인지 구분이 사라진다.
--
-- 타입은 DBML 그대로다: VARCHAR(n) · TIMESTAMPTZ · SMALLINT · BIGINT · BOOLEAN ·
-- FLOAT · DATE. sqlite 쪽(TEXT·INTEGER)과 다른 것이 정상이다.

-- ── main server 소유 (§1) ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS channel (
    channel_id   VARCHAR(20) PRIMARY KEY,
    display_name VARCHAR(50),
    connected_at TIMESTAMPTZ,
    status       VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS products (
    variant_row_id       VARCHAR(20) PRIMARY KEY,
    channel_product_id   VARCHAR(50) NOT NULL,
    channel_id           VARCHAR(20) NOT NULL REFERENCES channel(channel_id),
    channel_product_name TEXT,
    option_group_names   TEXT,
    channel_option_name  TEXT,
    sale_price           INTEGER,
    original_price       INTEGER,
    fetched_at           TIMESTAMPTZ,
    updated_at           TIMESTAMPTZ
);
-- ⚠️ PK 가 아니라 인덱스다 — 색상·사이즈 옵션이 여러 variant 로 붙어 같은 채널 상품
--    ID 를 공유한다. 유니크로 걸면 적재가 깨진다.
CREATE INDEX IF NOT EXISTS idx_products_channel_product ON products (channel_product_id);

CREATE TABLE IF NOT EXISTS mapped_data (
    variant_row_id     VARCHAR(20) PRIMARY KEY REFERENCES products(variant_row_id),
    product_group_id   VARCHAR(50) NOT NULL,
    mapping_method     VARCHAR(20),
    mapping_confidence FLOAT,
    mapped_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_mapped_data_group ON mapped_data (product_group_id);

CREATE TABLE IF NOT EXISTS orders (
    channel_id         VARCHAR(20) NOT NULL REFERENCES channel(channel_id),
    channel_product_id VARCHAR(50) NOT NULL,
    order_date         DATE NOT NULL,
    quantity           INTEGER NOT NULL,
    order_amount       BIGINT NOT NULL,
    created_at         TIMESTAMPTZ,
    PRIMARY KEY (channel_id, channel_product_id, order_date)
);

-- ⚠️ `product_group_id` 에 NOT NULL 이 **없다**(정본 그대로). 매핑 실패 행이 NULL 로
--    들어오면 우리 집계의 그룹 키가 비어 슬롯이 통째로 어긋난다 — `_build_inputs` 가
--    "상품매핑 없음" 으로 세고 분모에서 빼는 이유다. 적재 정책은 확인 대기(2026-08-16).
CREATE TABLE IF NOT EXISTS cs (
    id                 VARCHAR(20) PRIMARY KEY,
    channel_product_id VARCHAR(50),
    product_group_id   VARCHAR(50),
    channel_id         VARCHAR(20) NOT NULL REFERENCES channel(channel_id),
    content            TEXT NOT NULL,
    inquired_at        TIMESTAMPTZ NOT NULL,
    created_at         TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_cs_inquired_at ON cs (inquired_at);
CREATE INDEX IF NOT EXISTS idx_cs_group_channel ON cs (product_group_id, channel_id);
CREATE INDEX IF NOT EXISTS idx_cs_channel_product ON cs (channel_product_id);

-- ⚠️ cs 와 달리 발생 시각·적재 시각을 나누지 않고 `created_at` 단일 컬럼이다.
--    그래서 `02_ai_read_model.sql` 의 통합 뷰가 두 컬럼을 한 축으로 맞춘다.
CREATE TABLE IF NOT EXISTS reviews (
    id                 VARCHAR(20) PRIMARY KEY,
    channel_product_id VARCHAR(50),
    product_group_id   VARCHAR(50),
    channel_id         VARCHAR(20) NOT NULL REFERENCES channel(channel_id),
    content            TEXT NOT NULL,
    rating             SMALLINT,
    created_at         TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON reviews (created_at);
CREATE INDEX IF NOT EXISTS idx_reviews_group_channel ON reviews (product_group_id, channel_id);
CREATE INDEX IF NOT EXISTS idx_reviews_channel_product ON reviews (channel_product_id);

-- ── AI 노드 소유 (§1) ───────────────────────────────────────────────────────
--
-- 쓰기는 분류 워커만 한다(§5-2). 읽는 쪽(탐지 배치·CS 원문 조회·월간 집계)은 읽기 전용.

CREATE TABLE IF NOT EXISTS classified_item (
    item_id          VARCHAR(20) PRIMARY KEY,
    source           VARCHAR(10) NOT NULL,
    classified_at    TIMESTAMPTZ,
    prompt_version   VARCHAR(30),
    model_version    VARCHAR(50),
    pipeline_version VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS classified_item_aspect (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id      VARCHAR(20) NOT NULL REFERENCES classified_item(item_id),
    aspect       VARCHAR(10) NOT NULL,
    sentiment    SMALLINT NOT NULL,
    mixed_signal BOOLEAN
);
CREATE INDEX IF NOT EXISTS idx_classified_item_aspect_item
    ON classified_item_aspect (item_id);

CREATE TABLE IF NOT EXISTS classification_failure (
    item_id         VARCHAR(20) PRIMARY KEY,
    occurred_at     TIMESTAMPTZ,
    stage           VARCHAR(20) NOT NULL,
    error           TEXT NOT NULL,
    attempts        INTEGER NOT NULL DEFAULT 1,
    first_failed_at TIMESTAMPTZ NOT NULL,
    last_failed_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS classification_cursor (
    worker_id        VARCHAR(50) PRIMARY KEY,
    last_inquired_at TIMESTAMPTZ,
    last_item_id     VARCHAR(20),
    updated_at       TIMESTAMPTZ NOT NULL
);
