"""Raw DB 스키마 — 노션 「Raw DB 스키마 확정 (8/7)」 §2 를 그대로 옮긴 DDL.

우리가 정한 규칙이 아니라 확정 문서를 옮겨 적은 것이므로, 문서가 바뀌지 않는 한 이 파일도
바뀌지 않아야 한다.

소유권:
    main server 쓰기 : channel · products · mapped_data · orders · cs · reviews
    AI 노드 쓰기      : classified_item · classified_item_aspect ·
                       classification_failure · classification_cursor

**AI 소유 4개 + `voc_document` 뷰는 운영에서도 우리가 만든다** — `create_classified_tables()`
가 그 경로이고 여기 DDL 을 고치면 운영 스키마가 바뀐다. `create_source_tables()` 만 로컬·목
전용이다(목 파이프라인에서는 `scripts/mock_producer.py` 가 main server 자리를 대신한다).

`scripts/` 가 아니라 core 에 있는 이유는 쓰는 쪽과 읽는 쪽이 갈려 있어서다 — 스크립트에
두면 `app/` 이 import 할 수 없어 집계 쪽이 테이블·뷰 이름을 다시 적게 되고 스키마가 두 벌이
된다.

**DDL 은 백엔드 2종을 갈라서 낸다 — 한쪽으로 통일하지 말 것.** 데모(sqlite)가 그대로 돌아야
하고 운영은 Postgres 다. 문법이 갈리는 곳:

    CREATE VIEW IF NOT EXISTS   →  CREATE OR REPLACE VIEW   (Postgres 에 IF NOT EXISTS 없음)
    INTEGER PRIMARY KEY AUTOINCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY
    TEXT / INTEGER              →  VARCHAR(n) / TIMESTAMPTZ / SMALLINT / BOOLEAN

두 정의가 갈리면 `CREATE TABLE IF NOT EXISTS` 가 조용히 건너뛰어 **조회 단계에 가서야
드러난다.** `tests/test_raw_db_dialects.py` 가 두 판을 대조한다.

시각은 전부 **오프셋이 붙은 ISO 문자열**로 넣는다 — 오프셋 없이 넣으면 TIMESTAMPTZ 인 운영
컬럼에서 어느 지역 시각인지 알 수 없어 하루가 밀린다.
"""

from __future__ import annotations

from app.core import raw_db

# ── main server 소유 ─────────────────────────────────────────────────────────
#
# 아래 `REFERENCES` 는 **sqlite 에서 기본으로 안 걸린다**(연결마다 `PRAGMA foreign_keys=ON`
# 필요). 안 켜면 채널 오타가 조용히 통과해서 운영 Postgres 에 올라가서야 처음 터진다.

# channel_id 는 문자열 자체가 PK 이고 우리 `Channel` enum 값과 그대로 일치한다.
CHANNEL_DDL = """
CREATE TABLE IF NOT EXISTS channel (
    channel_id   TEXT PRIMARY KEY,
    display_name TEXT,
    connected_at TEXT,
    status       TEXT
);
"""

# 채널에 올라간 상품(variant) 카탈로그 — 채널 쪽 사실만 담는다. **어느 상품끼리 같은
# 상품인지는 여기 없다**(그 판단은 `mapped_data` 로 갈린다).
#
# channel_product_name  월간 리포트가 셀러에게 보여줄 표기명. 채널마다 다르다.
# updated_at            카탈로그는 가격 변동 등으로 원본이 바뀌는데 `mapped_data` 스냅샷은
#                       따라오지 않는다 — 두 테이블이 각각 언제 기준인지 가르는 값이다.
PRODUCTS_DDL = """
CREATE TABLE IF NOT EXISTS products (
    variant_row_id       TEXT PRIMARY KEY,
    channel_id           TEXT NOT NULL REFERENCES channel(channel_id),
    channel_product_id   TEXT NOT NULL,
    channel_product_name TEXT,
    option_group_names   TEXT,
    channel_option_name  TEXT,
    sale_price           INTEGER,
    original_price       INTEGER,
    fetched_at           TEXT,
    updated_at           TEXT
);
"""

# `channel_product_id` 는 **PK 가 아니라 인덱스**다 — 색상·사이즈 옵션이 여러 행으로 붙어
# 같은 채널 상품 ID 를 여러 variant 가 공유한다. 유니크로 걸면 적재가 깨진다.
PRODUCTS_CHANNEL_PRODUCT_INDEX = (
    "CREATE INDEX IF NOT EXISTS idx_products_channel_product "
    "ON products (channel_product_id);"
)

# 상품 매핑 결과(variant → 상품 그룹). **AI 노드가 만드는 값이 아니다** — 백엔드가 수행해
# 적재하고, 목 파이프라인에서만 `mock_producer` 가 그 자리를 대신한다.
#
# 이 테이블이 비면 **채널 간 비교가 통째로 무너진다** — 상품 하나가 채널마다 다른 그룹이
# 되어 편중형/전역형 판정도 채널 격차도 성립하지 않는다(실측: 매핑 없이 돌렸을 때 상세페이지
# RAG 조회 적중률 0%).
#
# mapping_method      slm_embedding / rule_naming / manual. `sim` 이 아니라 `slm` 이다.
# mapping_confidence  **참고용이다. 판정 기준으로 쓰지 않는다**(확정 문서 명시).
# mapped_at           매핑 시점. `products` 원본이 나중에 바뀌어도 이 값은 안 따라온다.
MAPPED_DATA_DDL = """
CREATE TABLE IF NOT EXISTS mapped_data (
    variant_row_id     TEXT PRIMARY KEY REFERENCES products(variant_row_id),
    product_group_id   TEXT NOT NULL,
    mapping_method     TEXT,
    mapping_confidence REAL,
    mapped_at          TEXT
);
"""

MAPPED_DATA_GROUP_INDEX = (
    "CREATE INDEX IF NOT EXISTS idx_mapped_data_group ON mapped_data (product_group_id);"
)

# CS 문의 원문 — 이상탐지·리포팅이 **분모를 세는 정본**이다.
#
# 분류 안 된 문의도 반드시 남는다. 분모가 "그 상품·채널의 총 문의 수"라 분류에 실패했거나
# 아무 aspect 에도 안 걸린 문의가 사라지면 부정률이 왜곡된다 — **이 테이블에서 행을 지우거나
# 숨기는 배치를 만들지 말 것.**
#
# inquired_at  문의 발생 시각. 35일 범위조회의 조건절이라 인덱스 필수.
# created_at   레코드 적재 시각. inquired_at 과 다를 수 있다.
CS_DDL = """
CREATE TABLE IF NOT EXISTS cs (
    id                 TEXT PRIMARY KEY,
    channel_product_id TEXT,
    product_group_id   TEXT,
    channel_id         TEXT REFERENCES channel(channel_id),
    content            TEXT NOT NULL,
    inquired_at        TEXT NOT NULL,
    created_at         TEXT
);
"""

# 리뷰 원문 — cs 와 같은 구조 + rating. 단 발생 시각·적재 시각을 나누지 않고 `created_at`
# 단일 컬럼이라, 아래 `VOC_DOCUMENT_VIEW` 가 두 컬럼을 하나의 축으로 맞춘다.
REVIEWS_DDL = """
CREATE TABLE IF NOT EXISTS reviews (
    id                 TEXT PRIMARY KEY,
    channel_product_id TEXT,
    product_group_id   TEXT,
    channel_id         TEXT REFERENCES channel(channel_id),
    content            TEXT NOT NULL,
    rating             INTEGER,
    created_at         TEXT NOT NULL
);
"""

# 채널별 주문 원본. 개별 주문건이 아니라 **그 날의 합산**이라 복합 PK 로 하루 한 행이다.
ORDERS_DDL = """
CREATE TABLE IF NOT EXISTS orders (
    channel_id         TEXT NOT NULL REFERENCES channel(channel_id),
    channel_product_id TEXT NOT NULL,
    order_date         TEXT NOT NULL,
    quantity           INTEGER NOT NULL,
    order_amount       INTEGER NOT NULL,
    created_at         TEXT,
    PRIMARY KEY (channel_id, channel_product_id, order_date)
);
"""

# ── AI 노드 소유 ─────────────────────────────────────────────────────────────

# 문의/리뷰 1건 = 1행. 원문 사본은 만들지 않고(원본 DB 에서 바로 읽는다) 채널·상품그룹·발생
# 시각도 cs/reviews 에 있으니 두지 않는다. item_id 는 `cs.id`/`reviews.id` 를 그대로
# 재사용한다 — 접두사 INQ-/RVW- 가 달라 합쳐도 충돌하지 않는다.
#
# **이 두 테이블로 분모를 세면 안 된다.** aspect 가 하나도 없는 문의는 자식 테이블에 0행이라
# 분모가 조용히 줄어든다. 분모는 cs/reviews 에서 세고 여기를 LEFT JOIN 해 분자만 가져온다.
#
# 버전 3종은 **감사용 메타가 아니라 조회 조건이다.** 탐지가 35일을 한 번에 읽어서 그 사이
# 분류기가 바뀐 행이 섞이면 부정률 변화의 원인이 고객인지 라벨러인지 구분되지 않는다 —
# Fisher 검정은 둘을 못 가르므로 **분류기 개선이 그대로 고객 이상 알림으로 발화한다.**
# 근거·적용 절차: `docs/classified_item_version_columns.md`
CLASSIFIED_ITEM_DDL = """
CREATE TABLE IF NOT EXISTS classified_item (
    item_id          TEXT PRIMARY KEY,
    source           TEXT NOT NULL,
    classified_at    TEXT,
    prompt_version   TEXT,
    model_version    TEXT,
    pipeline_version TEXT
);
"""

VERSION_COLUMNS = ("prompt_version", "model_version", "pipeline_version")
"""분류 산출물의 버전 3종. 적재·조회가 같은 목록을 봐야 한다."""


def active_version_predicate(alias: str = "ci") -> str:
    """"이 행이 활성 분류기로 만들어졌는가" SQL 술어. 파라미터는 `version_params()` 순서.

    적재(`scripts/`)와 조회(`app/`)가 **같은 술어를 써야 한다.** 각자 적으면 한쪽만
    고쳐졌을 때 조회가 0건이 되고, 그건 알림이 안 나가는 방향(미탐)이라 조용하다.
    `source` 마다 프롬프트가 달라(CS/리뷰) 값 하나로 못 거르므로 CASE 로 가른다.

    **`=` 가 아니라 null-safe 비교다.** `=` 를 쓰면 버전을 안 남기던 시절의 `NULL` 행이
    어느 쪽으로도 안 걸려 조용히 빠진다 — 가장 확실히 옛것인 행들이 하필 안 잡히는 형태다.

    **철자가 `IS NOT DISTINCT FROM` 인 이유 — 양쪽에서 같은 뜻인 유일한 철자다.** sqlite 는
    `IS` 를 null-safe 비교로 쓰지만 Postgres 에서 `IS` 는 `IS NULL` 계열 전용이라 `x IS ?`
    가 구문 오류다. 반대로 sqlite 3.39+ 는 이 철자를 `IS` 의 별칭으로 받는다. 그래서 DB 별로
    갈라 쓰는 코드도 파라미터 개수 변화도 없다 — `(a = b OR (a IS NULL AND b IS NULL))` 로
    풀면 `?` 가 두 배가 돼 `version_params()` 의 순서 계약이 깨진다.
    """
    return (
        f"{alias}.prompt_version IS NOT DISTINCT FROM"
        f" (CASE {alias}.source WHEN 'cs' THEN ? ELSE ? END)"
        f" AND {alias}.model_version IS NOT DISTINCT FROM ?"
        f" AND {alias}.pipeline_version IS NOT DISTINCT FROM ?"
    )


def version_params(
    prompt_cs: str, prompt_review: str, model: str, pipeline: str
) -> tuple[str, str, str, str]:
    """`active_version_predicate()` 의 `?` 에 넣을 값. **순서가 계약이다.**

    술어와 값을 한 파일에 두는 이유: 순서가 어긋나면 SQL 은 에러 없이 **다른 것을 비교**한다
    (전부 TEXT 라 타입으로도 안 걸린다). 그 결과는 조회 0건이고, 조용하다.
    """
    return prompt_cs, prompt_review, model, pipeline

# 1문의 : N aspect. JSON 한 컬럼에 안 몰고 정규화하는 이유는 이상탐지가 aspect 별
# GROUP BY 로 집계하기 때문이다. sentiment 는 -1/0/1, mixed_signal 은 리뷰 전용(CS 는 NULL).
CLASSIFIED_ITEM_ASPECT_DDL = """
CREATE TABLE IF NOT EXISTS classified_item_aspect (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id      TEXT NOT NULL REFERENCES classified_item(item_id),
    aspect       TEXT NOT NULL,
    sentiment    INTEGER NOT NULL,
    mixed_signal INTEGER,
    UNIQUE (item_id, aspect)
);
"""

# 분류 dead-letter. 이게 없으면 실패 건이 로그로만 남고 커서가 지나가 **영구 유실**된다 —
# 분모는 그대로인데 분자만 빠져 부정률이 조용히 과소추정된다. 남겨야 커버리지를 셀 수 있고
# 재처리할 수 있다(성공하면 그 행은 삭제).
#   stage    parse(스키마 변환 실패) / classify(LLM 호출·파싱 실패)
#   attempts 재처리 시도 횟수. 결정적 실패를 무한 재과금하지 않도록 상한을 건다.
FAILURE_DDL = """
CREATE TABLE IF NOT EXISTS classification_failure (
    item_id         TEXT PRIMARY KEY,
    occurred_at     TEXT,
    stage           TEXT NOT NULL,
    error           TEXT NOT NULL,
    attempts        INTEGER NOT NULL DEFAULT 1,
    first_failed_at TEXT NOT NULL,
    last_failed_at  TEXT NOT NULL
);
"""

# 어디까지 분류했는지 — Kafka 컨슈머 오프셋을 대체한다. `classified_item_aspect` INSERT 와
# 같은 트랜잭션에서 갱신해 원자성을 보장한다.
#
# 컬럼명이 `last_inquired_at` 인데 리뷰의 시각 컬럼은 `created_at` 이다(확정 문서의 이름을
# 그대로 따랐다). 의미는 "마지막으로 처리한 원문의 발생 시각" 이고 아래 뷰의 `occurred_at`
# 이 그 값이다.
CURSOR_DDL = """
CREATE TABLE IF NOT EXISTS classification_cursor (
    worker_id        TEXT PRIMARY KEY,
    last_inquired_at TEXT,
    last_item_id     TEXT,
    updated_at       TEXT NOT NULL
);
"""

# ── 읽기 모델 ────────────────────────────────────────────────────────────────

# cs ∪ reviews 통합 뷰. 두 테이블은 시각 컬럼명이 다른데(inquired_at / created_at) 분류
# 워커와 월간 집계는 둘 다 하나의 타임라인으로 훑어야 한다 — 호출부마다 UNION 을 다시 쓰면
# 시각 컬럼을 잘못 고르는 실수가 각자 생기므로 여기서 `occurred_at` 하나로 맞춘다.
#
# **이 뷰가 분모의 정본이다.** 분모와 분자를 한 쿼리로 묶지 말 것 — GROUP BY 에 aspect 가
# 들어간 채로 분모까지 세면 분류 안 된 문의가 빠진다.
VOC_DOCUMENT = "voc_document"
"""통합 뷰 이름. 조회하는 쪽은 문자열을 다시 적지 말고 이 상수를 쓴다."""

VOC_DOCUMENT_VIEW = f"""
CREATE VIEW IF NOT EXISTS {VOC_DOCUMENT} AS
    SELECT id                 AS item_id,
           'cs'               AS source,
           channel_id,
           channel_product_id,
           product_group_id,
           content,
           inquired_at        AS occurred_at
    FROM cs
    UNION ALL
    SELECT id,
           'review',
           channel_id,
           channel_product_id,
           product_group_id,
           content,
           created_at
    FROM reviews;
"""

SOURCE_INDEXES = [
    # 35일 배치의 핵심 조건절
    "CREATE INDEX IF NOT EXISTS idx_cs_inquired_at ON cs (inquired_at);",
    "CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON reviews (created_at);",
    # 집계 GROUP BY 단위와 일치
    "CREATE INDEX IF NOT EXISTS idx_cs_group_channel ON cs (product_group_id, channel_id);",
    "CREATE INDEX IF NOT EXISTS idx_reviews_group_channel ON reviews (product_group_id, channel_id);",
    # 채널 상품 단위 조회. `product_group_id` 는 비정규화라 상품매핑 전 구간에서는 비어
    # 있고, 그때 상품을 가리키는 축은 이쪽뿐이다. 확정 문서의 인덱스 요약표는 이상탐지
    # 조회 패턴만 추려서 이 둘이 없지만 DDL 전문과 컬럼표에는 있다.
    "CREATE INDEX IF NOT EXISTS idx_cs_channel_product ON cs (channel_product_id);",
    "CREATE INDEX IF NOT EXISTS idx_reviews_channel_product ON reviews (channel_product_id);",
]

CLASSIFIED_INDEXES = [
    # cs / reviews 와의 조인 키
    "CREATE INDEX IF NOT EXISTS idx_classified_item_aspect_item ON classified_item_aspect (item_id);",
    # 탐지의 활성 버전 필터와 워커의 stale 스캔이 이 세 컬럼을 **전부 등호로** 거른다.
    # 컬럼 순서는 술어의 비교 순서와 맞춰 둔다.
    (
        "CREATE INDEX IF NOT EXISTS idx_classified_item_versions"
        " ON classified_item (prompt_version, model_version, pipeline_version);"
    ),
]

# 원문 테이블 — 이게 없으면 워커가 읽을 것이 없다.
SOURCE_TABLES = ("cs", "reviews")

# ── Postgres 판 DDL ─────────────────────────────────────────────────────────
#
# 위 sqlite 판과 **테이블·컬럼 구성이 같아야 한다**(타입·자동증가 문법만 다르다).
# 타입은 노션 「RAW DB 스키마」(DDL 전문, DBML) 그대로다.
#
# `VARCHAR(n)` 은 넘치면 **Postgres 에서만** 적재가 실패한다(sqlite 의 TEXT 는 안 걸린다).
# 지금은 여유가 크지만(`classify_sentiment_v4` 21자 / VARCHAR(30)) 버전 문자열을 길게 지을
# 때 이 한도를 같이 볼 것.

_PG_CHANNEL_DDL = """
CREATE TABLE IF NOT EXISTS channel (
    channel_id   VARCHAR(20) PRIMARY KEY,
    display_name VARCHAR(50),
    connected_at TIMESTAMPTZ,
    status       VARCHAR(20)
);
"""

_PG_PRODUCTS_DDL = """
CREATE TABLE IF NOT EXISTS products (
    variant_row_id       VARCHAR(20) PRIMARY KEY,
    channel_id           VARCHAR(20) NOT NULL REFERENCES channel(channel_id),
    channel_product_id   VARCHAR(50) NOT NULL,
    channel_product_name TEXT,
    option_group_names   TEXT,
    channel_option_name  TEXT,
    sale_price           INTEGER,
    original_price       INTEGER,
    fetched_at           TIMESTAMPTZ,
    updated_at           TIMESTAMPTZ
);
"""

_PG_MAPPED_DATA_DDL = """
CREATE TABLE IF NOT EXISTS mapped_data (
    variant_row_id     VARCHAR(20) PRIMARY KEY REFERENCES products(variant_row_id),
    product_group_id   VARCHAR(50) NOT NULL,
    mapping_method     VARCHAR(20),
    mapping_confidence FLOAT,
    mapped_at          TIMESTAMPTZ
);
"""

_PG_CS_DDL = """
CREATE TABLE IF NOT EXISTS cs (
    id                 VARCHAR(20) PRIMARY KEY,
    channel_product_id VARCHAR(50),
    product_group_id   VARCHAR(50),
    channel_id         VARCHAR(20) REFERENCES channel(channel_id),
    content            TEXT NOT NULL,
    inquired_at        TIMESTAMPTZ NOT NULL,
    created_at         TIMESTAMPTZ
);
"""

_PG_REVIEWS_DDL = """
CREATE TABLE IF NOT EXISTS reviews (
    id                 VARCHAR(20) PRIMARY KEY,
    channel_product_id VARCHAR(50),
    product_group_id   VARCHAR(50),
    channel_id         VARCHAR(20) REFERENCES channel(channel_id),
    content            TEXT NOT NULL,
    rating             SMALLINT,
    created_at         TIMESTAMPTZ NOT NULL
);
"""

_PG_ORDERS_DDL = """
CREATE TABLE IF NOT EXISTS orders (
    channel_id         VARCHAR(20) NOT NULL REFERENCES channel(channel_id),
    channel_product_id VARCHAR(50) NOT NULL,
    order_date         DATE NOT NULL,
    quantity           INTEGER NOT NULL,
    order_amount       BIGINT NOT NULL,
    created_at         TIMESTAMPTZ,
    PRIMARY KEY (channel_id, channel_product_id, order_date)
);
"""

_PG_CLASSIFIED_ITEM_DDL = """
CREATE TABLE IF NOT EXISTS classified_item (
    item_id          VARCHAR(20) PRIMARY KEY,
    source           VARCHAR(10) NOT NULL,
    classified_at    TIMESTAMPTZ,
    prompt_version   VARCHAR(30),
    model_version    VARCHAR(50),
    pipeline_version VARCHAR(30)
);
"""

# `GENERATED BY DEFAULT`(ALWAYS 아님)인 이유는 골든 주입처럼 id 를 명시해 넣는 경로가 생겨도
# 막히지 않게 하려는 것이다. `mixed_signal` 은 BOOLEAN 이라 적재 쪽이 `int()` 로 캐스팅하면
# 타입 오류가 난다 — 파이썬 `bool` 을 그대로 넘겨야 양쪽이 다 받는다.
_PG_CLASSIFIED_ITEM_ASPECT_DDL = """
CREATE TABLE IF NOT EXISTS classified_item_aspect (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id      VARCHAR(20) NOT NULL REFERENCES classified_item(item_id),
    aspect       VARCHAR(10) NOT NULL,
    sentiment    SMALLINT NOT NULL,
    mixed_signal BOOLEAN,
    UNIQUE (item_id, aspect)
);
"""

_PG_FAILURE_DDL = """
CREATE TABLE IF NOT EXISTS classification_failure (
    item_id         VARCHAR(20) PRIMARY KEY,
    occurred_at     TIMESTAMPTZ,
    stage           VARCHAR(20) NOT NULL,
    error           TEXT NOT NULL,
    attempts        INTEGER NOT NULL DEFAULT 1,
    first_failed_at TIMESTAMPTZ NOT NULL,
    last_failed_at  TIMESTAMPTZ NOT NULL
);
"""

_PG_CURSOR_DDL = """
CREATE TABLE IF NOT EXISTS classification_cursor (
    worker_id        VARCHAR(50) PRIMARY KEY,
    last_inquired_at TIMESTAMPTZ,
    last_item_id     VARCHAR(20),
    updated_at       TIMESTAMPTZ NOT NULL
);
"""

# `OR REPLACE` 는 컬럼 이름·순서·타입이 같을 때만 통과하므로, 뷰 정의를 바꾸면 여기서
# `cannot change name of view column` 으로 시끄럽게 막힌다 — 조용히 옛 뷰가 남는 것보다 낫다.
_PG_VOC_DOCUMENT_VIEW = VOC_DOCUMENT_VIEW.replace(
    "CREATE VIEW IF NOT EXISTS", "CREATE OR REPLACE VIEW"
)

_SOURCE_DDL: dict[str, tuple[str, ...]] = {
    raw_db.SQLITE: (CHANNEL_DDL, PRODUCTS_DDL, MAPPED_DATA_DDL, CS_DDL, REVIEWS_DDL, ORDERS_DDL),
    raw_db.POSTGRES: (
        _PG_CHANNEL_DDL,
        _PG_PRODUCTS_DDL,
        _PG_MAPPED_DATA_DDL,
        _PG_CS_DDL,
        _PG_REVIEWS_DDL,
        _PG_ORDERS_DDL,
    ),
}

_CLASSIFIED_DDL: dict[str, tuple[str, ...]] = {
    raw_db.SQLITE: (
        CLASSIFIED_ITEM_DDL,
        CLASSIFIED_ITEM_ASPECT_DDL,
        FAILURE_DDL,
        CURSOR_DDL,
    ),
    raw_db.POSTGRES: (
        _PG_CLASSIFIED_ITEM_DDL,
        _PG_CLASSIFIED_ITEM_ASPECT_DDL,
        _PG_FAILURE_DDL,
        _PG_CURSOR_DDL,
    ),
}

_VOC_DOCUMENT_DDL: dict[str, str] = {
    raw_db.SQLITE: VOC_DOCUMENT_VIEW,
    raw_db.POSTGRES: _PG_VOC_DOCUMENT_VIEW,
}


def create_source_tables(conn) -> None:
    """main server 소유 테이블 + 통합 뷰. **운영에서는 안 불린다** — 목 프로듀서 전용이다.

    `products` 는 `channel` 다음, `mapped_data` 는 `products` 다음이어야 한다(FK 방향).
    다만 **sqlite 에서는 깨지는 곳이 CREATE 가 아니라 적재다** — 부모 테이블이 없어도
    `CREATE TABLE ... REFERENCES` 를 통과시키고 다음 INSERT 에서 터진다. Postgres 는 CREATE
    단계에서 바로 막는다.
    """
    dialect = raw_db.dialect_of(conn)
    for ddl in _SOURCE_DDL[dialect]:
        raw_db.execute_ddl(conn, ddl)
    for stmt in (*SOURCE_INDEXES, PRODUCTS_CHANNEL_PRODUCT_INDEX, MAPPED_DATA_GROUP_INDEX):
        raw_db.execute_ddl(conn, stmt)
    raw_db.execute_ddl(conn, _VOC_DOCUMENT_DDL[dialect])


def create_classified_tables(conn) -> None:
    """AI 노드 소유 테이블 + 우리 읽기 모델. 분류 워커가 부른다. **운영 경로다.**

    뷰도 함께 보장한다 — 워커가 자기가 만들지 않은 DB 에 붙는 경우가 있고(프로듀서 없이
    덤프만 받은 상태) 뷰가 없으면 조회가 통째로 실패한다.

    `IF NOT EXISTS` 라 **이미 있는 테이블은 손대지 않으므로** 호출 전에
    `find_legacy_tables()` 로 먼저 걸러야 한다. 동시 실행은 `raw_db.execute_ddl()` 이
    견딘다 — 워커가 CronJob 이라 겹쳐 뜰 수 있고 진 쪽이 죽으면 무한 재시도가 된다.
    """
    dialect = raw_db.dialect_of(conn)
    for ddl in _CLASSIFIED_DDL[dialect]:
        raw_db.execute_ddl(conn, ddl)
    for stmt in CLASSIFIED_INDEXES:
        raw_db.execute_ddl(conn, stmt)
    raw_db.execute_ddl(conn, _VOC_DOCUMENT_DDL[dialect])


# 구버전 raw DB 판별용 — 테이블마다 "8/7 확정 이후에만 있는" 컬럼 하나. 확정 전 구조로
# 만들어진 DB 가 팀원 로컬에 남아 있는데(`data/` 는 gitignore), 거기 대고
# `create_classified_tables()` 를 불러도 `IF NOT EXISTS` 가 옛 테이블을 그대로 두기 때문에
# 실패가 **한참 뒤 조회 단계**에서 `no such column` 으로 터진다.
#
# **마커는 그 테이블에 가장 나중에 들어온 컬럼이어야 한다.** 판정이 "마커가 없으면 옛것"
# 이라, 컬럼을 추가하고 마커를 안 옮기면 **그 사이 버전의 테이블이 전부 최신으로 통과한다.**
# 실제로 버전 컬럼 2개를 넣으면서 마커가 `prompt_version` 에 남아 있었고, 4컬럼 시절
# 테이블이 `find_legacy_tables() = []` 로 통과한 뒤 `no such column: model_version` 으로
# 죽었다 — 가드가 막으려던 바로 그 자리로 되돌아갔다.
LEGACY_MARKERS: dict[str, str] = {
    "classified_item": "pipeline_version",  # 구: prompt_version 만 있던 4컬럼
    "classification_failure": "item_id",  # 구: event_id PK
    "classification_cursor": "last_inquired_at",  # 구: last_occurred_at / last_event_id
}


# 컬럼만으로는 못 잡는 것 — **유니크 제약**. 컬럼이 다 있어도 이게 없으면 재분류가 같은
# `(item_id, aspect)` 를 중복 적재한다(워커의 "aspect 는 지우고 다시 넣는다" 가 이 제약을
# 전제로 짜여 있다). 없으면 탐지 분자가 부풀고, 그건 **오탐 방향이라 시끄럽지도 않다.**
#
# 우리가 만드는 테이블인데도 가드가 필요한 이유는, 인프라가 낡은 문서로 먼저 세워 뒀으면
# `CREATE TABLE IF NOT EXISTS` 가 조용히 건너뛰고 제약 없는 옛 모양이 남기 때문이다.
REQUIRED_UNIQUE_COLUMNS: dict[str, frozenset[str]] = {
    "classified_item_aspect": frozenset({"item_id", "aspect"}),
}


def find_legacy_tables(conn) -> list[str]:
    """확정 스키마 이전 구조로 남아 있는 AI 소유 테이블 이름. 없으면 빈 리스트.

    두 축을 본다 — `LEGACY_MARKERS` 의 마커 컬럼이 없거나 `REQUIRED_UNIQUE_COLUMNS` 의
    조합이 없으면 옛것이다. 없는 테이블은 대상이 아니다(새로 만들면 되는 정상 상태라,
    "있는데 모양이 옛것"인 경우만 골라낸다).

    스키마 조회를 `raw_db` 에 맡긴다 — 여기서 `PRAGMA` 를 직접 쓰면 **Postgres 에서 이 가드
    자신이 구문 오류로 죽는다.**
    """
    stale = []
    for table, marker in LEGACY_MARKERS.items():
        columns = raw_db.table_columns(conn, table)
        if columns and marker not in columns:
            stale.append(table)

    for table, required in REQUIRED_UNIQUE_COLUMNS.items():
        if table in stale or not raw_db.table_columns(conn, table):
            continue
        if required not in raw_db.unique_column_sets(conn, table):
            stale.append(table)
    return stale
